name: Demo

on:
  push:
    # branches:
    #   - dev
    #   - main

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3.0.2
        id: yarn-cache
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          ADBLOCK: true

      - name: Build Playground
        run: yarn build:playground

      - name: Echo release type
        run: echo ${{ github.ref }}

      - name: Echo release type
        run: echo ${{ github.base_ref }}

      - name: Echo release type
        run: echo ${{ github.head_ref }}

      - name: Echo release type
        run: echo ${{ github.ref_name }}

      - name: Echo release type
        run: echo ${{ github.ref_type }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: playground/dist
          CLEAN: true
          SINGLE_COMMIT: true
          TARGET_FOLDER: 'main'
      - name: Print the demo URL
        run: echo "✅ The demo has been deployed to https://$(cut -d'/' -f1 <<< $GITHUB_REPOSITORY).github.io/$(cut -d'/' -f2 <<< $GITHUB_REPOSITORY)/"
