name: release

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**.md'

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    environment: production

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3.0.2
        id: yarn-cache
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
        env:
          ADBLOCK: true

      - name: Build
        run: yarn build

      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          commit_pattern: "^v?(\\d+\\.\\d+\\.\\d+(?:-(?:alpha|beta)\\.\\d+)?)$"
          publish_command: 'yarn'
          publish_args: '--non-interactive --access=public --new-version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
